#!/usr/bin/env python3
"""Build the parts of a YSF air frame the HRI-200 does not hand over.

The radio strips sync, FICH and the DCH data channel before passing voice
to the PC, so a gateway going the other way — from the radio into a YSF
network — has to put them back. This module does that and nothing else.

    frame = build_frame(fi, fn, ft, dch, voice, dgid)

Everything here is a port of the encoders in MMDVMHost, by way of urfd,
and is checked against them: tests/test_ysf_frame.py replays 300 vectors
generated by urfd's own CYSFFICH::encode and CYSFPayload::writeVDMode2Data
and requires every byte to match.
"""

# ----------------------------------------------------------------------
# frame geometry

FRAME_LENGTH = 120
SYNC = bytes([0xD4, 0x71, 0xC9, 0x63, 0x4D])
SYNC_LENGTH = 5
FICH_LENGTH = 25
BLOCK_STRIDE = 18
DCH_LENGTH = 5
VCH_OFFSET = 35
VCH_LENGTH = 13
VCH_COUNT = 5

FI_HEADER, FI_COMMUNICATIONS, FI_TERMINATOR, FI_TEST = 0, 1, 2, 3
DT_VD_MODE1, DT_DATA_FR_MODE, DT_VD_MODE2, DT_VOICE_FR_MODE = 0, 1, 2, 3
MR_BUSY = 2

# Every interleaver here is the same read-out with a different width.
def _interleave(columns):
    return [2 * row + 40 * col for row in range(20) for col in range(columns)]


INTERLEAVE_5 = _interleave(5)      # FICH and the V/D mode 2 DCH
INTERLEAVE_9 = _interleave(9)      # the header and terminator payload

# The VCH interleaver is a different shape: 104 bits, four ways.
INTERLEAVE_VCH = [4 * k + base for base in range(4) for k in range(26)]

PAYLOAD_LENGTH = VCH_LENGTH * VCH_COUNT      # 65, what a D1E or D1R carries

# What urfd puts in the DT2 slot; not ASCII.
GPS_FILLER = bytes([0x52, 0x22, 0x61, 0x5F, 0x27, 0x03, 0x5E, 0x20, 0x20, 0x20])

WHITENING = bytes([0x93, 0xD7, 0x51, 0x21, 0x9C, 0x2F, 0x6C, 0xD0, 0xEF,
                   0x0F, 0xF8, 0x3D, 0xF1, 0x73, 0x20, 0x94, 0xED, 0x1E,
                   0x7C, 0xD8])

CALLSIGN_LENGTH = 10


# ----------------------------------------------------------------------
# bit helpers, MSB first throughout

def get_bit(data, i):
    return (data[i >> 3] >> (7 - (i & 7))) & 1


def set_bit(data, i, value):
    if value:
        data[i >> 3] |= 1 << (7 - (i & 7))
    else:
        data[i >> 3] &= ~(1 << (7 - (i & 7))) & 0xFF


def is_voice(block):
    """True if a 13-byte block is a well-formed V/D mode 2 VCH.

    After de-interleaving and removing the whitening, bits 0..80 fall into
    27 triplets that carry each data bit three times. Voice passes this at
    100 %, unrelated data at the 25 % a coin toss gives, which makes it a
    reliable filter for frames that hold no voice at all.
    """
    raw = [get_bit(block, i) for i in range(104)]
    vch = [raw[INTERLEAVE_VCH[i]] ^ get_bit(WHITENING, i) for i in range(104)]
    return all(vch[3 * i] == vch[3 * i + 1] == vch[3 * i + 2] for i in range(27))


def split_vch(payload):
    """Cut a 65-byte payload into its five 13-byte sections."""
    return [payload[VCH_LENGTH * i:VCH_LENGTH * (i + 1)]
            for i in range(VCH_COUNT)]


def is_voice_payload(payload):
    return (len(payload) == PAYLOAD_LENGTH
            and all(is_voice(b) for b in split_vch(payload)))


# ----------------------------------------------------------------------
# Golay (24,12)

_GENPOL = 0xC75
_X22 = 0x00400000
_X11 = 0x00000800
_MASK12 = 0xFFFFF800


def _syndrome_23127(pattern):
    aux = _X22
    if pattern >= _X11:
        while pattern & _MASK12:
            while not (aux & pattern):
                aux >>= 1
            pattern ^= (aux // _X11) * _GENPOL
    return pattern


def golay_23127(data):
    """12 data bits to a 23-bit codeword, data in the high bits."""
    code = (data << 11) & 0x7FFFFF
    return code | _syndrome_23127(code)


def golay_24128(data):
    """The same with an overall parity bit appended."""
    code = golay_23127(data)
    parity = bin(code).count("1") & 1
    return (code << 1) | parity


# ----------------------------------------------------------------------
# CRC-16/CCITT, the variant that stores the result low byte last

_CRC_TABLE = []
for _b in range(256):
    _c = _b << 8
    for _ in range(8):
        _c = ((_c << 1) ^ 0x1021) & 0xFFFF if _c & 0x8000 else (_c << 1) & 0xFFFF
    _CRC_TABLE.append(_c)


def add_ccitt162(data, length):
    """Write the CRC of data[:length-2] into the last two bytes."""
    crc = 0
    for i in range(length - 2):
        crc = ((crc & 0xFF) << 8) ^ _CRC_TABLE[((crc >> 8) & 0xFF) ^ data[i]]
    crc = ~crc & 0xFFFF
    data[length - 1] = crc & 0xFF
    data[length - 2] = (crc >> 8) & 0xFF


# ----------------------------------------------------------------------
# rate 1/2, constraint length 5 convolutional code

def convolve(data, nbits):
    """Encode nbits of data into 2*nbits bits."""
    out = bytearray((2 * nbits + 7) // 8)
    d1 = d2 = d3 = d4 = 0
    k = 0
    for i in range(nbits):
        d = get_bit(data, i)
        set_bit(out, k, (d + d3 + d4) & 1)
        k += 1
        set_bit(out, k, (d + d1 + d2 + d4) & 1)
        k += 1
        d4, d3, d2, d1 = d3, d2, d1, d
    return out


def _spread(convolved, table, nbytes):
    """Interleave bit pairs into the field they are sent in."""
    out = bytearray(nbytes)
    j = 0
    for n in table:
        set_bit(out, n, get_bit(convolved, j))
        set_bit(out, n + 1, get_bit(convolved, j + 1))
        j += 2
    return bytes(out)


# ----------------------------------------------------------------------
# FICH

class Fich(object):
    """The 25-byte frame information channel.

    Field names follow the YSF specification; the bit positions are those
    MMDVMHost uses.
    """

    def __init__(self, fi=FI_COMMUNICATIONS, cs=2, cm=0, bn=0, bt=0, fn=0,
                 ft=6, dt=DT_VD_MODE2, mr=MR_BUSY, dev=False, sql=False,
                 sq=0, voip=False):
        self.fi, self.cs, self.cm = fi, cs, cm
        self.bn, self.bt = bn, bt
        self.fn, self.ft = fn, ft
        self.dt, self.mr = dt, mr
        self.dev, self.sql, self.sq, self.voip = dev, sql, sq, voip

    def _raw(self):
        f = bytearray(6)
        f[0] = ((self.fi << 6) & 0xC0) | ((self.cs << 4) & 0x30) \
            | ((self.cm << 2) & 0x0C) | (self.bn & 0x03)
        f[1] = ((self.bt << 6) & 0xC0) | ((self.fn << 3) & 0x38) \
            | (self.ft & 0x07)
        f[2] = (0x40 if self.dev else 0) | ((self.mr << 3) & 0x38) \
            | (0x04 if self.voip else 0) | (self.dt & 0x03)
        f[3] = (0x80 if self.sql else 0) | (self.sq & 0x7F)
        return f

    def encode(self):
        f = self._raw()
        add_ccitt162(f, 6)

        blocks = [((f[0] << 4) & 0xFF0) | ((f[1] >> 4) & 0x00F),
                  ((f[1] << 8) & 0xF00) | f[2],
                  ((f[3] << 4) & 0xFF0) | ((f[4] >> 4) & 0x00F),
                  ((f[4] << 8) & 0xF00) | f[5]]

        conv = bytearray(13)
        for i, block in enumerate(blocks):
            code = golay_24128(block)
            conv[3 * i] = (code >> 16) & 0xFF
            conv[3 * i + 1] = (code >> 8) & 0xFF
            conv[3 * i + 2] = code & 0xFF
        return _spread(convolve(conv, 100), INTERLEAVE_5, 25)


# ----------------------------------------------------------------------
# DCH

def encode_dch(text):
    """Encode ten characters into the 5 bytes each block carries.

    Returns the 25 bytes that go in front of the five voice sections, five
    at a time.
    """
    field = bytearray(13)
    raw = text if isinstance(text, bytes) else \
        ("%-10s" % text)[:CALLSIGN_LENGTH].encode("ascii", "replace")
    raw = (raw + b" " * CALLSIGN_LENGTH)[:CALLSIGN_LENGTH]
    for i in range(CALLSIGN_LENGTH):
        field[i] = raw[i] ^ WHITENING[i]
    add_ccitt162(field, 12)
    field[12] = 0x00
    return _spread(convolve(field, 100), INTERLEAVE_5, 25)


def encode_fr_data(dt):
    """Encode 20 bytes into the 9 bytes each block carries in FR mode.

    Header and terminator frames carry no voice: both halves of every
    block are data, nine bytes from each of two of these.
    """
    field = bytearray(25)
    raw = ("%-20s" % dt)[:20].encode("ascii", "replace")
    for i in range(20):
        field[i] = raw[i] ^ WHITENING[i]
    add_ccitt162(field, 22)
    field[22] = 0x00
    return _spread(convolve(field, 180), INTERLEAVE_9, 45)


# ----------------------------------------------------------------------

def build_header_frame(source, gateway, terminator=False, dgid=0):
    """Assemble the frame that opens or closes a transmission.

    Neither carries voice. The first ten characters name the gateway and
    the next ten the station being heard, which is what a reflector reads
    to label the stream.
    """
    frame = bytearray(FRAME_LENGTH)
    frame[0:SYNC_LENGTH] = SYNC

    fich = Fich(fi=FI_TERMINATOR if terminator else FI_HEADER, fn=0, ft=7,
                sql=dgid > 0, sq=dgid)
    frame[SYNC_LENGTH:SYNC_LENGTH + FICH_LENGTH] = fich.encode()

    csd1 = ("%-10s" % gateway)[:10] + ("%-10s" % source)[:10]
    first = encode_fr_data(csd1)
    second = encode_fr_data(" " * 20)

    base = SYNC_LENGTH + FICH_LENGTH
    for i in range(VCH_COUNT):
        at = base + BLOCK_STRIDE * i
        frame[at:at + 9] = first[9 * i:9 * (i + 1)]
        frame[at + 9:at + 18] = second[9 * i:9 * (i + 1)]
    return bytes(frame)


def dch_for_frame(fn, source, gateway):
    """Which of the data-channel fields a given frame number carries.

    The rotation follows what MMDVMHost and urfd emit, so a reflector sees
    the fields where it expects them.
    """
    if fn == 0:
        return "**********"
    if fn == 1:
        return source
    if fn in (2, 5):
        return gateway
    if fn == 6:
        return GPS_FILLER
    return " " * 10


def build_frame(voice, fi=FI_COMMUNICATIONS, fn=0, ft=6, dch="**********",
                dgid=0):
    """Assemble a 120-byte V/D mode 2 frame.

    voice: the 65 bytes the HRI-200 delivers in a D1R frame, which are the
    five VCH sections already in on-air form and go in untouched.
    """
    if len(voice) != VCH_LENGTH * VCH_COUNT:
        raise ValueError("voice is %d bytes, expected %d"
                         % (len(voice), VCH_LENGTH * VCH_COUNT))

    frame = bytearray(FRAME_LENGTH)
    frame[0:SYNC_LENGTH] = SYNC

    fich = Fich(fi=fi, fn=fn, ft=ft, sql=dgid > 0, sq=dgid)
    frame[SYNC_LENGTH:SYNC_LENGTH + FICH_LENGTH] = fich.encode()

    data = encode_dch(dch)
    base = SYNC_LENGTH + FICH_LENGTH
    for i in range(VCH_COUNT):
        at = base + BLOCK_STRIDE * i
        frame[at:at + DCH_LENGTH] = data[DCH_LENGTH * i:DCH_LENGTH * (i + 1)]
        frame[at + DCH_LENGTH:at + BLOCK_STRIDE] = \
            voice[VCH_LENGTH * i:VCH_LENGTH * (i + 1)]
    return bytes(frame)
